{% set name = "feflow" %}
{% set version = "0.2.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/feflow/archive/{{ version }}.tar.gz
  sha256: 286e3c1cfc541121ade923fdf45d3beca120777cf61026c5d928619448c9db1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >={{ python_min }}
    - gufe >=1.9.0,<2
    - numpy
    - openfe >=1.10.0,<2  # TODO: Remove once we don't depend on openfe
    - openff-units
    - openmm
    - openmmtools >=0.23.0
    - pydantic >=2,<3
    - pymbar >4.0

test:
  imports:
    - feflow
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/OpenFreeEnergy/feflow
  summary: Recipes and protocols for molecular free energy calculations using the openmmtools/perses and Open Free Energy toolkits
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dotsdl
    - ijpulidos
    - IAlibay
    - mikemhenry
