{% set name = "feflow" %}
{% set version = "0.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/feflow/archive/{{ version }}.tar.gz
  sha256: 095261627480d4c0a82485c3707968a0b943243c2fff510d6eccff47176fc888

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >={{ python_min }}
    - gufe >=1.4,<1.7
    - numpy
    - openfe >=1.1.0  # TODO: Remove once we don't depend on openfe
    - openff-units
    - openmm
    - openmmtools >=0.23.0
    - pydantic >=1.10.17
    - pymbar >4.0

test:
  imports:
    - feflow
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/OpenFreeEnergy/feflow
  summary: Recipes and protocols for molecular free energy calculations using the openmmtools/perses and Open Free Energy toolkits
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dotsdl
    - ijpulidos
    - IAlibay
    - mikemhenry
