{% set name = "feflow" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/feflow/archive/{{ version }}.tar.gz
  sha256: 284a6926df4fc6163be1227f2772d32d6227015e4f4a9a2e031a106c54e6b716

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python {{ python_min }}
    - gufe >=1.0
    - numpy
    - openfe >=1.0  # TODO: Remove once we don't depend on openfe
    - openff-units
    - openmm
    - openmmforcefields >=0.14.1  # TODO: remove when upstream deps fix this
    - openmmtools >=0.23.0
    - pydantic >=1.10.17
    - pymbar ~=3.0

test:
  imports:
    - feflow
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-xdist
  commands:
    - pytest -n auto -v --pyargs feflow

about:
  home: https://github.com/OpenFreeEnergy/feflow
  summary: Recipes and protocols for molecular free energy calculations using the openmmtools/perses and Open Free Energy toolkits
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ijpulidos
    - IAlibay
    - mikemhenry
